trapexit/mergerfs

README.md, src/fs.cpp, src/fs.hpp, src/rename.cpp
Return EXDEV if directories of tragets differ. If the old and new path exist in the same directory first rename each old found by the policy and then unlink/rmdir any new on a drive which didn't rename. The unlink/rmdir will occur only if there were no rename errors. Any failures of unlink/rmdir are ignored. The last rename error is returned.
=> rework rename

README.md, src/gidcache.cpp, src/gidcache.hpp
Uses fixed storage so as to not require C++11 local thread storage or memory allocation.
=> rewrite gid cache system

src/fs.cpp, src/fs.hpp, src/policy_all.cpp, src/policy_eplfs.cpp, src/policy_epmfs.cpp, src/policy_erofs.cpp, src/policy_ff.cpp, src/policy_invalid.cpp, src/policy_lfs.cpp, src/policy_mfs.cpp, src/policy_newest.cpp
Used statvfs to also check for existance vs lstat. On dead symlinks
this resulted in ENOENT making certain functions fail.
closes #239
=> clearly separate usage of statvfs from stat for file existance

src/gidcache.cpp
Fixes group permission issues on 32bit Linux platforms.
=> use SYS_setgroup32 syscall if available. closes #319

src/create.cpp, src/link.cpp, src/mkdir.cpp, src/mknod.cpp, src/rename.cpp, src/symlink.cpp
currently the error is ignored and it was expected the primary call would
fail. problem is it returns confusing errors as a result. (eg ENOENT vs EPERM)
=> return clonepath errors

README.md, man/mergerfs.1, src/fs_inode.hpp, src/getattr.cpp, src/readdir.cpp
creates a 64bit inode value from the underlying device value + original inode
final_ino = orig_ino | (dev << 32)
not perfect but given few filesystems use 64bit inodes nor is st_dev more than 16bit usually it should be fine
=> support setting of inodes (using use_ino option)

Makefile
These are more like LIBS rather than LDFLAGS.
They are used just in one place,
so simply put them inline.
Also, use LDFLAGS provided by the user during actual link.
This helps users pass their own LDFLAGS.
For example, this is important on Gentoo,
where LDFLAGS='-Wl,-O1 -Wl,--as-needed' is passed by default.
=> Makefile: don't touch LDFLAGS

src/fs_clonefile.cpp, src/fs_copy_file_range.cpp, src/fs_copy_file_range.hpp, src/fs_copy_file_range_linux.icpp, src/fs_copy_file_range_unsupported.icpp, src/fs_copyfile.cpp, src/fs_copyfile.hpp, src/fs_ficlone.cpp, src/fs_ficlone.hpp, src/fs_ficlone_linux.icpp, src/fs_ficlone_unsupported.icpp
If available FICLONE and copy_file_range will be tried in addition to sendfile
when copying data between two files. The fallback is a tradition read/write
loop. On systems that support these it should improve performance.
=> add FICLONE and copy_file_range to clonefile

src/fasthash.cpp, src/fasthash.h, src/hashset.hpp, src/khash.h, src/readdir.cpp
Use fasthash64 to hash filenames to uint64_t and store in khash
set. Significantly reduces malloc/free'ing and memory usage.
=> optimize readdir file dedup

README.md, man/mergerfs.1, src/getxattr.cpp, src/option_parser.cpp, src/setxattr.cpp
ENOSYS is the correct return to short circuit xattr calls at the kernel. Not ENOTSUP.
=> change xattr setting notsup to nosys

libfuse/lib/fuse_lowlevel.c
=> fix outarg size to accomidate newer fuse_kernel.h on older platforms

libfuse/lib/fuse.c, tests/TEST_unlink_rename
There was a bug with renaming over opened unlinked files which have been marked "hidden". This was an edgecase with the change to remove .fuse_hidden files.
=> fix renaming over open unlinked file

src/option_parser.cpp
Inadvertently added backwards incompatibility after removing unneeded arguments. Setting atomic_o_trunc, big_writes, or max_writes= will do nothing but not error.
=> accept old arguments for backwards compatibility

src/fuse_ioctl.cpp
Turns out certain ioctl calls check the effective user id (FS_IOC_SETFLAGS).
=> set uid & gid when calling ioctl

Makefile
Currently, reinstalling or upgrading mergerfs via the Makefile gives an error, because the symlink mount.mergerfs already exists:
```
ln -s "mergerfs" "/usr/local/bin/mount.mergerfs"
ln: /usr/local/bin/mount.mergerfs: File exists
gmake: *** [Makefile:153: install-mount.mergerfs] Error 1
```
This fixes that error by removing and recreating the symlink if it already exists, rather than erroring.
As this is a Makefile it would also be possible to make it do nothing if the symlink already exists, rather than recreating it. It seemed like the general pattern of the Makefile was not to worry about such things, but I could do it that way if you want.
=> Force symlink creation (don't error if it already exists)

libfuse/Makefile, libfuse/include/fuse_lowlevel.h, libfuse/lib/fuse.c
* Change fuse_ino_t to uint64_t
* Change id generation to 64bit
* Randomize generation value (should help with NFS)
=> improve nodeid generation

libfuse/lib/fuse.c
While this replicates the original libfuse2 behavior it can result in bad data being sent to the kernel. A future patch will address this in a safer way.
=> temporary fix for short readdirs on NFS

libfuse/include/fuse_dirents.h, libfuse/include/kvec.h, libfuse/lib/fuse.c, libfuse/lib/fuse_dirents.c
This removes the risk of corrupted data being sent back to the kernel
should it use the offset from one opendir-readdir in another. In this case
it would at most skip dirents.
According to the standards the offset is only valid when used within
the opendir -> releasedir but NFS uses offsets across independent
calls.
=> readdir: add dirent index array

Makefile, libfuse/Makefile
This changeset allows for to change default CFLAGS/CXXFLAGS/LDFLAGS as well as set custom `ar` using environmental variables, while still adding the additional non-optional flags even if user pushes their own flags. Unless those variables are set, buildsystem of libfuse and mergerfs acts the same way it did before those changes.
Those changes exist to fix bugs reported under:
- https://bugs.gentoo.org/725978
- https://bugs.gentoo.org/728158
=> Makefiles fixes: support environmental passed $AR, $CFLAGS, $CXXFLAGS and $LDFLAGS

src/wyhash.h
mode 0 is not intended for unaligned buffers
=> wyhash: use safety mode 1

README.md
Have added the relative option for rsync. Previously it would dump all files into the root of the backing drive, adding relative puts it into the same subdirectory as it was located in on the cache drive.
=> Update percentage full expiring script

Makefile, README.md, libfuse/Makefile, libfuse/include/fuse.h, libfuse/lib/fuse.c, man/mergerfs.1, src/config.cpp, src/config.hpp, src/config_follow_symlinks.cpp, src/config_follow_symlinks.hpp, src/config_link_exdev.cpp, src/config_link_exdev.hpp, src/config_rename_exdev.cpp, src/config_rename_exdev.hpp, src/enum.hpp, src/fs_mkdir.hpp, src/fs_mkdir_as_root.hpp, src/fs_symlink.hpp, src/fuse_getattr.cpp, src/fuse_link.cpp, src/fuse_rename.cpp, src/fuse_rmdir.cpp, src/fuse_symlink.cpp, src/fuse_symlink.hpp, src/ghc/filesystem.hpp
* follow-symlinks: allows mergerfs to transparently follow symlinks
* link-exdev: in the event a link returns EXDEV create a symlink instead
* rename-exdev: in the event a rename returns EXDEV move the oldpath and create a symlink for the newpath
=> new features: follow-symlinks, rename-exdev, link-exdev

src/fuse_ioctl.cpp
While they were going to be the new way of interacting with the runtime config
I've decided to use toml based config for mergerfs v3. In that case all updates
will happen through the config file and ioctl will only be used to load/reload
the config rather than a key:value like API.
=> Remove config ioctl calls

src/fuse_link.cpp
While more efficient calling regular getattr (stat) leads to incorrect
information being returned and would not work correctly when using
symlinkify.
=> Call FUSE getattr rather than syscall for extra logic

src/fuse_link.cpp, src/fuse_symlink.cpp, src/fuse_symlink.hpp
Using getattr when follow-symlink is enabled causes invalid type to the kernel
if symlink pointed to non-symlink.
=> Fix query of attr during symlink

libfuse/lib/fuse.c
As done in https://github.com/libfuse/libfuse/pull/636
=> Change ENOENT to ESTALE for looking up paths to handle rename race conditions

libfuse/lib/fuse.c
In currently unknown situations '..' for node 1 can be requested. The root node is the only node without a parent which causes mergerfs to crash when requested as it doesn't expect such a request. This may need to be addressed in the future in a different way but for now return ENOENT.
=> Return ENOENT when dotdot for root node requested

README.md, libfuse/lib/mount_bsd.c, libfuse/lib/mount_generic.c, libfuse/lib/mount_util.c, libfuse/lib/mount_util.h, libfuse/util/fusermount.c, libfuse/util/mount_util.c, src/option_parser.cpp
This makes it like all other filesystems and brings it into alignment with libfuse3's behavior.
=> Remove 'nonempty' argument

src/fuse_ioctl.cpp
mergerfs tries to pass through ioctl calls but due to the complexity of btrfs calls their is risk of segfaults. In the future it may be required to whitelist all supported ioctl calls.
=> Return NOTTY for all btrfs ioctl calls

src/branches.cpp, tests/tests.cpp
Motivating case:
```
$ ./mergerfs -o config=any.conf aaa testmnt
terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::substr: __pos (which is 2) > this->size() (which is 0)
Aborted (core dumped)
```
The content of the config file is irrelevant, the relevant stack is:
```
#10 0x000000000040cc4e in Branches::Impl::from_string (this=0x680540, s_="") at src/branches.cpp:316
#11 0x000000000040d8e7 in Branches::from_string (this=0x7fffffffc500, str_="") at src/branches.cpp:381
#12 0x000000000042da04 in Config::operator= (this=0x7fffffffc4d0, cfg_=...) at src/config.cpp:193
#13 0x000000000042ecab in Config::from_stream (this=0x666d80 <Config::_singleton>, istrm_=..., errs_=0x7fffffffd4b0) at src/config.cpp:302
#14 0x000000000042f93e in Config::from_file …
```
=> Fix config file parsing

src/branches.cpp, src/config.cpp
All tools only read from srcmounts and the current setup had a bug which caused branch mode and minfreespace to be stripped when using config file.
=> Make srcmounts readonly

README.md, libfuse/Makefile, libfuse/include/fuse.h, libfuse/include/fuse_lowlevel.h, libfuse/include/fuse_msgbuf.h, libfuse/lib/bounded_queue.hpp, libfuse/lib/bounded_thread_pool.hpp, libfuse/lib/fuse.c, libfuse/lib/fuse_loop_mt.cpp, libfuse/lib/fuse_msgbuf.cpp, libfuse/lib/fuse_mt.c, libfuse/lib/fuse_signals.c, libfuse/lib/lock.h, libfuse/lib/make_unique.hpp, libfuse/lib/node.c, libfuse/lib/node.h, libfuse/lib/scope_guard.hpp, libfuse/lib/syslog.c, libfuse/lib/syslog.h, man/mergerfs.1, src/config.cpp, src/config.hpp, src/fuse_ioctl.cpp, src/mergerfs.cpp, src/option_parser.cpp
Yes, these are unrelated changes but somehow ended up being prototyped together and I'm too lazy to separate them.
=> Add manual GC triggering + configurable process queue depth

libfuse/lib/fuse_msgbuf.cpp
std::atomic_uint64_t missing in some older distros
=> Fix build on older distros due to std::atomic definitions

README.md
Clarifies some points around cache.files and parallel-direct-writes. See commit messages for details:
Tl;dr:
- Make it clear which kernel versions support `parallel-direct-writes`
~- Steer people to use `cache.files=off` instead of `direct_io`~
~- Clarify which each `cache.files` implies, so people with existing mount options can (hopefully) say, I can consolidate my mount flags into `cache.files=foo`~
- Make it clear that per-process will act the same as `cache.files=off` is the process name does not match
=> Docs: clarify parallel-direct-writes and cache.files

tools/preload.c
O_TMPFILE could be redirected as well but for now lets leave it going through mergerfs to just fix the lack of proper setting of mode.
=> Special case O_TMPFILE in preload

tools/mergerfs.percent-full-mover
The mergerfs.percent-full-mover script is missing the --relative flag for rsync.  
It currently moves all files into the root of the destination.  Adding the --relative flag fixes that, and paths are then correctly preserved.
=> Add missing --relative flag to rsync in percent-full mover script

libfuse/Makefile, libfuse/include/fuse.h, libfuse/include/maintenance_thread.hpp, libfuse/lib/fuse.cpp, libfuse/lib/fuse_loop.cpp, libfuse/lib/maintenance_thread.cpp, mkdocs/docs/config/options.md, mkdocs/docs/known_issues_bugs.md, src/config.cpp, src/config.hpp, src/config_gidcache.cpp, src/config_gidcache.hpp, src/fuse_ioctl.cpp, src/gidcache.cpp, src/gidcache.hpp, src/mergerfs.cpp, src/ugid.cpp
* Use concurrent_flat_map to build a global cache rather than per thread.
* Create global maintanence thread manager for clearing unused cache entries.
=> Update the secondary group cache

mkdocs/docs/quickstart.md, src/config.cpp
This changes will allow to have empty lines in `.ini` configs.
It also show that comments are supported in the docs.
=> Allow empty lines in config ini files

libfuse/include/fs_dirent64.hpp
Worked fine on my machine where padding seemed to be all zeroed out but that doesn't appear to be the case elsewhere.
Could try
https://codeberg.org/jbruchon/libjodycode/src/branch/master/dir.c#L92-L110 but needs to be tested.
=> Fix dirent64::namelen calculation
