trapexit/mergerfs

Makefile
README.md
mergerfs.spec

Thanks to @joe-lawrence for the initial pull request.

add building of rpm

---

Makefile
src/access.cpp
src/chmod.cpp
src/chown.cpp
src/create.cpp
src/getattr.cpp
src/getxattr.cpp
src/init.cpp
src/ioctl.cpp
src/link.cpp
src/listxattr.cpp
src/mkdir.cpp
src/mknod.cpp
src/open.cpp
src/readdir.cpp
src/readlink.cpp
src/removexattr.cpp
src/rename.cpp
src/rmdir.cpp
src/setxattr.cpp
src/statfs.cpp
src/symlink.cpp
src/truncate.cpp
src/ugid.hpp
src/ugid_linux.hpp
src/ugid_linux.ipp
src/ugid_rwlock.hpp
src/ugid_rwlock.ipp
src/unlink.cpp
src/utimens.cpp

make changing credentials opportunistic + per thread setgroups cache

---

README.md
src/getattr.cpp
src/init.cpp
src/ioctl.cpp
src/listxattr.cpp
src/option_parser.cpp
src/setxattr.cpp

include default_permissions in default arguments

---

src/access.cpp
src/chmod.cpp
src/chown.cpp
src/link.cpp
src/mkdir.cpp
src/mknod.cpp
src/removexattr.cpp
src/rename.cpp
src/rmdir.cpp
src/rv.hpp
src/setxattr.cpp
src/symlink.cpp
src/truncate.cpp
src/unlink.cpp
src/utimens.cpp

all action functions return success should at least one succeed

---

src/link.cpp

have link act similar to rename

---

src/policy_epmfs.cpp

Inadvertently removed after restructuring policy.

re-add minfreespace check to epmfs policy

---

README.md
man/mergerfs.1
src/policy.cpp
src/policy.hpp
src/policy_epall.cpp
src/policy_eprand.cpp

mostly to allow creating files randomly in preexisting directories.

add epall and eprand policies

---

README.md

https://lkml.org/lkml/2016/9/14/527

add information about page cache kernel panic bug

---

debian/control

add fuse to debian pkg dependency

---

src/fs.cpp
src/fs.hpp
src/fs_glob.cpp
src/fs_glob.hpp
src/option_parser.cpp
src/setxattr.cpp

keep literal when glob fails

---

README.md
src/branch.cpp
src/branch.hpp
src/policy_all.cpp
src/policy_epall.cpp
src/policy_epff.cpp
src/policy_eplfs.cpp
src/policy_eplus.cpp
src/policy_epmfs.cpp
src/policy_ff.cpp
src/policy_lfs.cpp
src/policy_lus.cpp
src/policy_mfs.cpp
src/policy_newest.cpp

rename NW (no write) to NC (no create)

---

src/fs_cow.cpp

remove O_LARGEFILE

---

libfuse/include/fuse.h
libfuse/lib/fuse.c
src/endian.hpp
src/fs_base_ioctl.hpp
src/fuse_ioctl.cpp

https://lwn.net/Articles/575846

fix FS_IOC_{GET,SET}{FLAGS,VERSION} ioctl calls

---

src/fs_clonefile.cpp

fall back to other file copy methods in clonefile

---

src/config.hpp
src/option_parser.cpp

fix setting of fsname

---

src/mergerfs.cpp

fixes #616 
May revisit issue in the future.

remove 'remote' flock support

---

Makefile

fix mount.mergerfs generation

---

libfuse/include/fuse.h
libfuse/lib/fuse.c
src/fuse_prepare_hide.cpp
src/fuse_prepare_hide.hpp

Hopefully addresses the race condition. In the least cleans up when node is freed.

fix for unlink race condition

---

README.md
man/mergerfs.1

Also some additional "why use mergerfs over X?"

README.md: add human readable versions of some errno references

---

src/option_parser.cpp

option_parser: return 0 when requesting help or version

---

src/fuse_chmod.cpp
src/fuse_chown.cpp
src/fuse_link.cpp
src/fuse_mkdir.cpp
src/fuse_mknod.cpp
src/fuse_removexattr.cpp
src/fuse_rename.cpp
src/fuse_rmdir.cpp
src/fuse_setxattr.cpp
src/fuse_symlink.cpp
src/fuse_truncate.cpp
src/fuse_unlink.cpp
src/fuse_utimens.cpp
src/policy_rv.hpp

chmod, chown, removexattr, setxattr, truncate, utimens:
* if no errors: return 0
* if no successes: return first error
* if file acted on was the same as related search function: return its value
* return 0
rmdir, unlink:
* if no errors: return 0
* return first error

rework some function error handling

---

src/policy_eppfrd.cpp
src/policy_msppfrd.cpp
src/policy_pfrd.cpp

pfrd: fix mod by zero error when all branches are filtered

---

libfuse/lib/fuse.c

The 32 byte array is below the average size so those 32 bytes are wasted a
large portion of the time.

Remove embedded name in node struct

---

README.md

At some point this should be settable via mergerfs.

Update README.md regarding readahead

---

libfuse/lib/fmp.h
libfuse/lib/fuse.c
libfuse/lib/helper.c

Also remove debug mode from forcing foreground mode

Rework node slab garbage collection to limit blocking work threads

---

README.md

sorry, i'm a grammar nerd with ocd :-)

small grammar correction to README file

---

README.md
src/branches.cpp
src/branches.hpp
src/config.cpp
src/config.hpp
src/fs_pathvector.hpp
src/fs_wait_for_mount.cpp
src/fs_wait_for_mount.hpp
src/mergerfs.cpp
src/nonstd/expected.hpp
src/nonstd/optional.hpp
src/syslog.cpp
src/syslog.hpp

branches-mount-timeout=UINT64 in seconds (default: 0)

Add option to wait for branches to become new mounts

---

README.md
src/config.cpp
src/config.hpp
src/mergerfs.cpp

Allow setting of scheduling priority

---

README.md
src/config.cpp
src/config.hpp
src/config_cachefiles.cpp
src/config_set.cpp
src/config_set.hpp
src/fs_openat.hpp
src/fuse_create.cpp
src/fuse_open.cpp
src/mergerfs.cpp
src/procfs_get_name.cpp
src/procfs_get_name.hpp
src/str.cpp
src/str.hpp

Allows chosing page caching based on process name.

Add "per-process" file caching feature

---

libfuse/include/fuse.h
libfuse/include/fuse_lowlevel.h
libfuse/lib/fuse.c
libfuse/lib/fuse_lowlevel.c
src/fuse_removemapping.cpp
src/fuse_removemapping.hpp
src/fuse_setupmapping.cpp
src/fuse_setupmapping.hpp
src/fuse_syncfs.cpp
src/fuse_syncfs.hpp
src/fuse_tmpfile.cpp
src/fuse_tmpfile.hpp
src/mergerfs.cpp

* setupmapping
* removemapping
* syncfs
* tmpfile

Add callbacks for newer functions

---

libfuse/lib/fuse.c
src/fuse_ioctl.cpp
src/gidcache.cpp
src/gidcache.hpp
src/mergerfs.cpp
src/ugid.cpp
src/ugid_linux.hpp
src/ugid_linux.icpp

Add ability to invalidate gid cache on demand

---

.gitignore
mkdocs/mkdocs.yml

fix edit uri

---

libfuse/lib/cpu.cpp
libfuse/lib/cpu.hpp
mkdocs/docs/config/options.md
mkdocs/docs/faq/technical_behavior_and_limitations.md
mkdocs/docs/related_projects.md
mkdocs/docs/setup/build.md
mkdocs/docs/setup/installation.md
src/fs_readahead.cpp
src/fs_umount2.hpp
tools/preload.c

First draft. Need to investigate why upstream patches include certain function that appear to exist in FreeBSD 14.2.

Improve FreeBSD compatibility

---

mkdocs/docs/setup/installation.md

Closes #1396 , relates to #1398
Re-ordered, condensed the debian install sections. Nice to see you recently added NIX.
Preview of changes: https://oregonpillow.github.io/setup/installation/

Readability changes to mkdocs installation

---

libfuse/include/fuse.h
src/fh.hpp
src/fileinfo.hpp
src/fs_inode.cpp
src/fs_inode.hpp
src/fuse_create.cpp
src/fuse_fgetattr.cpp
src/fuse_getattr.cpp
src/fuse_open.cpp
src/fuse_readdir_cor.cpp
src/fuse_readdir_cosr.cpp
src/fuse_readdir_seq.cpp
src/fuse_statx.cpp
src/fuse_symlink.cpp
src/nonstd/string_view.hpp

Use hashing of branch path rather than use st_dev.

Change the "devino" inode calculation

---

mkdocs/docs/config/export-support.md
mkdocs/docs/config/kernel-permissions-check.md
mkdocs/mkdocs.yml
src/config.cpp
src/config.hpp
src/option_parser.cpp

Defaults true but there might be some situations where it is useful to disable.

Add config option to control default_permissions

---

src/branches.cpp
src/fs_glob.cpp
src/option_parser.cpp

* Skip non-directories when loading branches
* Warn if branch doesn't exist
* Add braces to globbing

Misc cleanup

---

Makefile
mergerfs.spec
mkdocs/build-venv
mkdocs/docs/support.md
src/fsck_mergerfs.hpp
src/mergerfs.cpp
src/mergerfs_api.cpp
src/mergerfs_api.hpp
src/mergerfs_collect_info.cpp
src/mergerfs_collect_info.hpp
src/mergerfs_fsck.cpp
src/mergerfs_fsck.hpp
src/mergerfs_ioctl.hpp

A tool to collect info for support requests.

Add mergerfs.collect-info

---

src/mergerfs.cpp
src/oom.cpp
src/oom.hpp

To limit risk of killing by OOM Killer.

Add setting of oom_score_adj

---

mkdocs/regenerate-docs

Not pretty but works. Can automate it later once confirmed to be what I want.

Add script to generate docs from scratch and push to github

---

src/ioprio.cpp

Was not available on some platforms

Remove need for and use of ioprio header
